//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode2022 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultInputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultInputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode2022.DefaultInputs", typeof(DefaultInputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5474
        ///4920
        ///5381
        ///8650
        ///11617
        ///7193
        ///8161
        ///
        ///10747
        ///5855
        ///13827
        ///6294
        ///13437
        ///8125
        ///
        ///6913
        ///6443
        ///3431
        ///5357
        ///1579
        ///3590
        ///4471
        ///4971
        ///4055
        ///4937
        ///2514
        ///1679
        ///2917
        ///
        ///4203
        ///4433
        ///8798
        ///5838
        ///2031
        ///8765
        ///5107
        ///6055
        ///2482
        ///6266
        ///
        ///4646
        ///4705
        ///5183
        ///1707
        ///3676
        ///2042
        ///4140
        ///3321
        ///1899
        ///3055
        ///3327
        ///3944
        ///3879
        ///2981
        ///
        ///59238
        ///
        ///11748
        ///22005
        ///
        ///6389
        ///4630
        ///1443
        ///14530
        ///9588
        ///
        ///10578
        ///8843
        ///10344
        ///6289
        ///10444
        ///7615
        ///9510
        ///
        ///9351
        ///3942
        ///5896
        ///4692
        ///10110
        ///4125
        ///1161
        ///8261
        ///
        ///22239
        ///
        ///5485
        ///1528
        ///1288
        ///4749
        ///3742
        ///586 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01 {
            get {
                return ResourceManager.GetString("Day01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B Y
        ///A Y
        ///B Z
        ///A Z
        ///A Y
        ///B Z
        ///C X
        ///C X
        ///C X
        ///C Y
        ///C Z
        ///B Y
        ///C Y
        ///C Z
        ///A Y
        ///B Y
        ///C Y
        ///B Y
        ///B Y
        ///B Y
        ///C X
        ///B Z
        ///A X
        ///A Z
        ///C Z
        ///C Y
        ///C Y
        ///B Y
        ///B X
        ///C Z
        ///B Y
        ///B Y
        ///C Y
        ///B Y
        ///B Z
        ///B Z
        ///B Y
        ///A Y
        ///A Y
        ///B Z
        ///B Y
        ///B Y
        ///B Y
        ///C Y
        ///A Y
        ///B Y
        ///C Z
        ///B Y
        ///B Y
        ///A Z
        ///B Y
        ///A Y
        ///B Y
        ///B Z
        ///C Y
        ///C Z
        ///A Z
        ///C Z
        ///B Y
        ///A X
        ///C Z
        ///A X
        ///A Z
        ///B Y
        ///B Y
        ///A Y
        ///C Z
        ///B Y
        ///B Z
        ///B Z
        ///B X
        ///C Y
        ///B Y
        ///A Y
        ///A Y
        ///B Y
        ///A Z
        ///B X
        ///B Y
        ///B Y
        ///C Y
        ///C Z
        ///A Z
        ///B Y
        ///A Y
        ///B Z
        ///B Y
        ///B Y
        ///B Y
        ///C X
        ///C Y
        ///B Y
        ///B Y
        ///B Z
        ///B Y
        ///C X
        ///B Y
        ///B Y
        ///C Z
        ///C Z
        ///A X
        ///A X
        ///A  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day02 {
            get {
                return ResourceManager.GetString("Day02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vvMQnwwvrwWNfrtZJfppmSfJSmSg
        ///BzGqjlBqBBmztHNFzDHg
        ///llRCPlTPPqBjPhqhlBRBClhqWcTWrWNcMbQbdrdLccccrnvM
        ///wMhwbTWpQjbpWHMQppzTHhjtlCjPSSJCCtlqRlJVFJFt
        ///ggdvvnvDgdDmNcBrrcDntFRFqHJJtSJqvlVSRlJq
        ///fggNNffGmcBrmBfcDzzzpHbsGTpszwwTbp
        ///BPdPPBggrPtrpbtvPBBdgrFmhhQThGGlbbTZnzZQzZfn
        ///ccjWRJVNcTGmnWWFmh
        ///DMNmsMHwRNBrggdPDPdt
        ///TfsfHLQbBtBFQbQsBmPwwlnPGZFwwdwWFZZw
        ///MRpcvJMJVSMrVMpVSvhhnclwgWwDZgWgWgWglwcG
        ///GCzjRJjVjSSrvfNQtLmQNsQbjB
        ///FrSPFjtVvwsqSwcG
        ///hDHdWDngpgZTDgHzzHwNNqlwNvZJlGqcQGsl
        ///wDzLTDHgFffLtRft
        ///CnCJNVqvCBJBNZmf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day03 {
            get {
                return ResourceManager.GetString("Day03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day04 {
            get {
                return ResourceManager.GetString("Day04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day05 {
            get {
                return ResourceManager.GetString("Day05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day06 {
            get {
                return ResourceManager.GetString("Day06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day07 {
            get {
                return ResourceManager.GetString("Day07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day08 {
            get {
                return ResourceManager.GetString("Day08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day09 {
            get {
                return ResourceManager.GetString("Day09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day10 {
            get {
                return ResourceManager.GetString("Day10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day11 {
            get {
                return ResourceManager.GetString("Day11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day12 {
            get {
                return ResourceManager.GetString("Day12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day13 {
            get {
                return ResourceManager.GetString("Day13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day14 {
            get {
                return ResourceManager.GetString("Day14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day15 {
            get {
                return ResourceManager.GetString("Day15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day16 {
            get {
                return ResourceManager.GetString("Day16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day17 {
            get {
                return ResourceManager.GetString("Day17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day18 {
            get {
                return ResourceManager.GetString("Day18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day19 {
            get {
                return ResourceManager.GetString("Day19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day20 {
            get {
                return ResourceManager.GetString("Day20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day21 {
            get {
                return ResourceManager.GetString("Day21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day22 {
            get {
                return ResourceManager.GetString("Day22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day23 {
            get {
                return ResourceManager.GetString("Day23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day24 {
            get {
                return ResourceManager.GetString("Day24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Day25 {
            get {
                return ResourceManager.GetString("Day25", resourceCulture);
            }
        }
    }
}
